config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about' , to: 'pages#about'
  #resources :brands, only: [:show, :index, :new, :create, :edit, :update]
  #resources :devices, only:[:show, :index, :new, :create, :edit, :update]

  resources :brands do
  resources :devices
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :devices

    validates :brand_name, presence: true, length: {minimum: 3, maximum: 30} 
    validates :origin_country, presence: true, length: {minimum: 3, maximum: 30}
end

app/models/device.rb
class Device < ApplicationRecord
    belongs_to :brand
   
    validates :brand_name, presence: true, length: {minimum: 4,maximum: 30}
    validates :device_name, presence: true, length: {minimum: 1,maximum: 30}
    validates :screen_size, presence: true, length: {minimum: 3,maximum: 10}
    validates :camera, presence: true, length: {minimum: 1,maximum: 10}
    validates :battery, presence: true, length: {minimum: 3,maximum: 10}
    validates :brand_id, presence: true, length: {minimum: 1,maximum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    
    def show
        @brand = Brand.find(params[:id])
    end

    def index
        @brands = Brand.all
    end

    def new
        @brand = Brand.new
    end

    def edit
        @brand = Brand.find(params[:id])
    end

    def create
        @brand = Brand.new(params.require(:brand).permit(:brand_name, :origin_country))
        if @brand.save
            flash[:notice] = "Brand Inserted Successfully!!"
            redirect_to @brand
        else
            render 'new'
        end
    end

    def update
       @brand = Brand.find(params[:id])
       if @brand.update(params.require(:brand).permit(:brand_name, :origin_country))
            flash[:notice] = "Brand was updated Successfully!!"
            redirect_to brands_path
        else
            render 'edit'
        end 
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

    def index
        @brand = Brand.find(params[:brand_id])
        @devices = @brand.devices
    end

    def show
        @device = Device.find(params[:id])
    end

    def new
        @device = Device.new
    end

    def edit
        @device = Device.find(params[:id])
    end

    def create
        @device = Brand.new(params.require(:device).permit(:brand_name,:device_name,:screen_size,:camera,:battery,:brand_id))
        if @device.save
            flash[:notice] = "Device Inserted Succesfully."
            redirect_to @device
        else
            render 'new'
        end
    end

    def update
        @device = Device.find(params[:id])
        if @device.update(params.require(:device).permit(:brand_name,:device_name,:screen_size,:camera,:battery,:brand_id))
            flash[:notice] = "Device Updated Succesfully."
            redirect_to devices_path
        else
            render 'edit'
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home

    end

    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/brands/edit.html.erb
<h1>Edit Brand.</h1>

<% if @brand.errors.any? %>
    <h3>Brand info is not being saved, please have a look at following instructions.</h3>
    <ul>
        <%@brand.errors.full_messages do |msg|%>
            <li><%= msg%></li>
        <%end%>
    </ul>
<%end%>

<%= form_with(model: @brand, local: true) do |fm|%>
    <p>
        <%= fm.label :brand_name%><br/>
        <%= fm.text_field :brand_name%>
        <br/><br/>
        <%= fm.label :origin_country%><br/>
        <%= fm.text_field :origin_country%>
    </p>
    <br/>
    <p>
        <%= fm.submit%>
    </p>
<%end%>

<%= link_to 'Cancel & Return to Brands Listing Page.', brands_path%>

app/views/brands/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
  <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Brands listing page</h1>
  <!--<%= link_to 'Add New Brand', new_brand_path(@brands), class: "text-indigo-500 inline-flex items-center pr-2"%>-->
  <!--<a class="text-indigo-500 inline-flex items-center pr-2", href="/brands/new">Add New Brand</a> -->
  <%= link_to 'Add New Brand', new_brand_path(@brands), class: "text-indigo-500 inline-flex items-center pr-2"%>
    <div class="flex flex-wrap -m-4">
    <% @brands.each do |brand| %>
      <div class="p-4 lg:w-1/3">
        <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
          <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">Brand Name</h2>
          <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3"><%= brand.brand_name %></h1>
           <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">Origin Country</h2>
          <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3"><%= brand.origin_country %></h1>
          <%= link_to 'Show', brand_path(brand), class: "text-indigo-500 inline-flex items-center pr-2"%>
          <%= link_to 'Edit', edit_brand_path(brand), class: "text-indigo-500 inline-flex items-center pr-2"%>

          <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0" href="/brands/<%= brand.id %>/devices">Devices</a>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</section>

app/views/brands/new.html.erb
<h1>Add a new Brand</h1>

<% if @brand.errors.any? %>
    <h3>Brands are not being saved, please have a look at following instructions.</h3>
    <ul>
        <%@brand.errors.full_messages do |msg|%>
            <li><%= msg%></li>
        <%end%>
    </ul>
<%end%>
 
<%= form_with scope: :brand, url: brands_path, local: true do |f| %>
  <p> 
    <%= f.label :brand_name %><br/> 
    <%= f.text_field :brand_name %>
  </p>
  <p>
    <%= f.label :origin_country %><br/> 
    <%= f.text_field :origin_country %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/brands/show.html.erb
<h2><strong>Mobiles list.</strong></h2><br><br>

<h3>Mobile Brands</h3><br>

<%= @brand.brand_name%> | <%= @brand.origin_country%>

<%= link_to 'Edit', brand_path(@brand)%>

app/views/devices/edit_dev.html.erb
<h1>Edit Device.</h1>

<% if @device.errors.any? %>
    <h3>Device info is not being saved, please have a look at following instructions.</h3>
    <ul>
        <%@device.errors.full_messages do |msg|%>
            <li><%= msg%></li>
        <%end%>
    </ul>
<%end%>

<%= form_with(model: @brand, local: true) do |fm|%>
      <p> 
    <%= f.label :brand_name %><br/> 
    <%= f.text_field :brand_name %>
  </p>

  <p>
    <%= f.label :device_name %><br/> 
    <%= f.text_field :device_name %>
  </p>

  <p>
    <%= f.label :screen_size %><br/> 
    <%= f.text_field :screen_size %>
  </p>

  <p>
    <%= f.label :camera %><br/> 
    <%= f.text_field :camera %>
  </p>

  <p>
    <%= f.label :battery %><br/> 
    <%= f.text_field :battery %>
  </p>

   <p>
    <%= f.label :brand_id %><br/> 
    <%= f.text_field :brand_id %>
  </p>
  <p>
    <%= f.submit %> 
  </p>

<%end%>

<%= link_to 'Cancel & Return to Brands Listing Page.', devices_path%>

app/views/devices/index.html.erb
<html>
<h1>Welcome to Devices</h1>

<ul>
  <% if @devices.count > 0 %>
    <% @devices.each do |device| %>
    <div class="grid text-center">
      <div class="g-col-6 g-col-md-4">
        <li>
        <p>Device Brand Name: <%= device.brand_name %></p>
        <p>Device Name: <%= device.device_name %></p>
        <p>Screen Size: <%= device.screen_size %></p>
        <p>Camera: <%= device.camera %></p>
        <p>Battery: <%= device.battery %></p>
        <a href="/brands/<%= device.brand_id %>/devices/<%= device.id %>">Show</a> |
        <a href="/brands/<%=device.brand_id%>/devices/<%=device.id%>/edit">Edit Device</a>
        <!-- <%= link_to 'Edit Device', edit_brand_device_path(device), class: "text-indigo-500 inline-flex items-center pr-2"%> | -->
        <!-- <a href="/brands/<%=device.brand_id%>/devices/new">Create New Device</a> -->
        <%= link_to 'Add new Device', new_brand_device_path(device), class: "text-indigo-500 inline-flex items-center pr-2"%>
        
      </li>
      <hr>
      </div>
    </div>

      
    <% end %>
  <% else %>
    <h2>No Devices Found</h2>
  <% end %>
</ul>
</html>

app/views/devices/new_dev.html.erb
<h1>Add a Device</h1>

<% if @device.errors.any? %>
    <h3>Device are not being saved, please have a look at following instructions.</h3>
    <ul>
        <%@device.errors.full_messages do |msg|%>
            <li><%= msg%></li>
        <%end%>
    </ul>
<%end%>

<%= form_with scope: :device, url: devices_path, local: true do |f| %>
  <p> 
    <%= f.label :brand_name %><br/> 
    <%= f.text_field :brand_name %>
  </p>

  <p>
    <%= f.label :device_name %><br/> 
    <%= f.text_field :device_name %>
  </p>

  <p>
    <%= f.label :screen_size %><br/> 
    <%= f.text_field :screen_size %>
  </p>

  <p>
    <%= f.label :camera %><br/> 
    <%= f.text_field :camera %>
  </p>

  <p>
    <%= f.label :battery %><br/> 
    <%= f.text_field :battery %>
  </p>

   <p>
    <%= f.label :brand_id %><br/> 
    <%= f.text_field :brand_id %>
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/devices/show.html.erb
<h2><strong>Device Information.</strong></h2>

<ul>
    <li>Brand Name: <%= @device.brand_name%></li>
    <li>Device Name: <%= @device.device_name%></li>
    <li>Screen Size: <%=@device.screen_size%></li>
    <li>Battery: <%=@device.battery%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GSMArena</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
    
  </body>
</html>

app/views/pages/about.html.erb
<h3>Hola amigos! This is Mobiles listing page</h3>

<%= link_to 'Brands Listing Page', brands_path%> | 
<%= link_to 'Home', root_path%>

app/views/pages/home.html.erb
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">GSM Arena</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <%= link_to 'Brands Listing Page', brands_path, class: "mr-5 hover:text-gray-900"%>
      <%= link_to 'About', about_path, class: "mr-5 hover:text-gray-900"%>
    </nav>
  </div>
</header>

<section class="text-gray-600 body-font">
  <div class="container px-5 pt-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">What is GSM Arena?</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">A Rails Application that shows basic information of Cellphone brands and their devices.</p>
    </div>
  </div>
</section>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
      <!--<h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Slow-carb next level shoindxgoitch ethical authentic, scenester sriracha forage.</h1> -->
      <button class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Button</button>
    </div>
  </div>
</section> 